// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDBHPqlxGk5eDzrkFCFtpztpXeHmyQug',
    appId: '1:966054026115:android:f1857b87b7177d807434b6',
    messagingSenderId: '966054026115',
    projectId: 'smart-library-s50-nextshelf',
    storageBucket: 'smart-library-s50-nextshelf.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMw8VjBT6fPc66Ndy2Vm3aJXc2dEU5dUo',
    appId: '1:966054026115:web:2212dcaa123a48d27434b6',
    messagingSenderId: '966054026115',
    projectId: 'smart-library-s50-nextshelf',
    authDomain: 'smart-library-s50-nextshelf.firebaseapp.com',
    storageBucket: 'smart-library-s50-nextshelf.firebasestorage.app',
    measurementId: 'G-19EZFHK6S3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4x1hdIKFWBhB0i5mAh9O3nlSJMiYYG4',
    appId: '1:966054026115:ios:a975738b714aea5d7434b6',
    messagingSenderId: '966054026115',
    projectId: 'smart-library-s50-nextshelf',
    storageBucket: 'smart-library-s50-nextshelf.firebasestorage.app',
    iosBundleId: 'com.example.smartLibraryFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4x1hdIKFWBhB0i5mAh9O3nlSJMiYYG4',
    appId: '1:966054026115:ios:a975738b714aea5d7434b6',
    messagingSenderId: '966054026115',
    projectId: 'smart-library-s50-nextshelf',
    storageBucket: 'smart-library-s50-nextshelf.firebasestorage.app',
    iosBundleId: 'com.example.smartLibraryFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMw8VjBT6fPc66Ndy2Vm3aJXc2dEU5dUo',
    appId: '1:966054026115:web:6d7afa3bb69e9af17434b6',
    messagingSenderId: '966054026115',
    projectId: 'smart-library-s50-nextshelf',
    authDomain: 'smart-library-s50-nextshelf.firebaseapp.com',
    storageBucket: 'smart-library-s50-nextshelf.firebasestorage.app',
    measurementId: 'G-XT2L8M5SWK',
  );

}